### ISSUE TITLE
About bsp for SAM4s

### ISSUE THREAD

**Issue by euripedesrocha** [AdaCore/embedded-runtimes#1]
Since last month I'm working on ravenscar support for SAM4L. I'm now moving the code, generated with svd2ada and based on stm32. 
The SAM4S ravenscar profile here has a diferent style from STM32, specifically s-sam4s.ads vs s-stm32.ads.

Which of them is supposed to be the "standard" in the future?

**Comment by lambourg** [comment]
The main difference between the two is that s-stm32.ads uses the specs generated via svd2ada, while s-sam4s is still hand-crafted.

In the future, we'll certainly continue towards using the generated specs: this is more reliable and faster than hand writing the register definitions. On the other hand, it might be easier for you to start from the sam4s bsp, as it must be very close to what you have.

**Comment by euripedesrocha** [comment]
Ok. I'll keep my present approach. I just need to finish the clock aspects at s-sam4l and s-textio. I'll send a pull request when done.
