### ISSUE TITLE
Support for HiFive1 board

### ISSUE THREAD

**Issue by embeddedden** [AdaCore/embedded-runtimes#15]
Hello, could you add support for the board? I mean full support: compiler, all peripheral supported (UART, SPI, GPIO) and sfp and full runtimes. Is it possible in a month or two? I would be glad to participate with the board in makewithada, but I need SPI, math library and threads support (implementing all this for a novice would take a lot of time).

I think this board is ideally fit to makewithada: to show that new software can be easily created with the language. At the same time, it is not so true for STM32 boards - they have much more capabilities to support, and also more libraries, a code generator and tutorials in Internet but for C language (so it is harder to utilize all the possibilities of these boards in pure Ada). 

If such a port is created, my project will show how to utilize most of its possibilities to create safe and reliable software.

Thanks.

**Comment by Fabien-Chouteau** [comment]
Hi Denis,

This is not on our road map at the moment. What is available so far is a Zero FootPrint run-time and a couple of drivers (GPIO, UART) in the [Ada_Drivers_Library](https://github.com/AdaCore/Ada_Drivers_Library/tree/master/arch/RISC-V/SiFive/drivers). Very soon I will document the procedure to build the compiler and run an example.

There's plenty of other platforms to use for the competition if the support of this one is not complete enough for you. On the other side adding more support for this micro-controller can be a good contribution for the competition.

Have fun!
