### ISSUE TITLE
UInt16 definition missing ?

### ISSUE THREAD

**Issue by huegene** [AdaCore/embedded-runtimes#7]
I am not certain of this beeing a bug or it beeing on purpose but the 

type UInt16 is mod 2**16
with Size => 16;

is missing in the common/i-bit_types.ads definition.

**Comment by Fabien-Chouteau** [comment]
Hi @huegene ,

UInt16 is not defined in common/i-bit_types.ads but there's "Short" instead.

Note that the last version of svd2Ada will now use a UInt16 type, either generated or in a package that you specify with the switch "--base-types-package=".

Also, the package i-bit_types.ads is deprecated, you should not use it.

Regards,
