### ISSUE TITLE
Support for the STM32F446

### ISSUE THREAD

**Issue by mterron** [AdaCore/embedded-runtimes#8]
Could you add support for this MCU and also for the nucleo board that goes with it?

Thanks

**Comment by Fabien-Chouteau** [comment]
Hello @mterron ,

It's not on our roadmap and I'm not aware of anybody working on it.

If you want to work on it we will be happy to help you. Since this MCU is in the STM32F4 it should be fairly easy to add support for it. I suggest you have a look at the other STM32F4 support to begin with.

Regards,

**Comment by Fabien-Chouteau** [comment]
We are also going to change the way run-times are built so it might be easier for you to support this MCU in a few months/weeks.

**Comment by mterron** [comment]
Good to know, happy to give it a go. Do you have an idea when this new process is going to be in place? Also are you going to write some documentation? Some of the current practices are a bit obscure, specially when it comes to the options to pass to svd2ada to generate compatible files.

**Comment by Fabien-Chouteau** [comment]
> Good to know, happy to give it a go. Do you have an idea when this new process is going to be in place? 

It should be ready around May.

> Also are you going to write some documentation? Some of the current practices are a bit obscure, specially when it comes to the options to pass to svd2ada to generate compatible files.

Yes, we will improve all this.

Regards,

**Comment by osannolik** [comment]
I have started adding support for stm32f446, but only for my own board, not for the Nucleo board. Could be a good start though. 
https://github.com/osannolik/embedded-runtimes

**Comment by Fabien-Chouteau** [comment]
@osannolik sounds good. You have a custom designed board?

**Comment by osannolik** [comment]
@Fabien-Chouteau Yes it is a board designed for controlling brushless DC motors, so not really a general development board unfortunately. https://hackaday.io/project/19826-brushless-dc-motor-controller

**Comment by Fabien-Chouteau** [comment]
@osannolik great! Are you participating to the [Make with Ada competition](makewithada.org) with this project?

**Comment by osannolik** [comment]
Yep, that is my plan! What branch do you think I should fork from? Initially I made the changes to master, but I am having some trouble compiling tasks with it (I get the error "too many arguments in call to 'Create_Restricted_Task'"). Now I see that the branch with the latest commits is the gpl2017_uninstall. Maybe I should base my changes on that. Sorry for being slightly off topic.

**Comment by Fabien-Chouteau** [comment]
> Yep, that is my plan! 

Great! It will be nice to see custom hardware used in the competition.

> What branch do you think I should fork from? Initially I made the changes to master, but I am having some trouble compiling tasks with it (I get the error "too many arguments in call to 'Create_Restricted_Task'"). Now I see that the branch with the latest commits is the gpl2017_uninstall. Maybe I should base my changes on that. Sorry for being slightly off topic.

If you use the GNAT GPL 2017 release you should use the gpl2017 branch.

**Comment by Fabien-Chouteau** [comment]
Closing, this repository is deprecated.
